anuncio/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as django_views
from . import views


app_name = 'anuncio'

urlpatterns = [

    #path('', views.IndexView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', django_views.LoginView.as_view(template_name="anuncio/login.html"), name='login'),
    path('logout/', django_views.LogoutView.as_view(next_page="/anuncio/"), name='logout'),
    path('sobre/', views.sobre  ,name='sobre'),
    path('categoria/add/',  views.CategoriaView.as_view(), name='add_categoria'),
    path('', views.index, name='index'),
]

siteanuncio/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
	path('',include('anuncio.urls')),
    path('admin/', admin.site.urls),
]

anuncio/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import (AbstractBaseUser, UserManager, PermissionsMixin)
from django.core import validators
import re

"""
class CadastroUsuario(models.Model):

	name = models.CharField(verbose_name=('Nome Completo'),max_length=100)
	contato = models.CharField(verbose_name=('Contato'),max_length=100)
	endereco = models.TextField(verbose_name=('Endereço'),max_length=100)
	email = models.EmailField(verbose_name=('Email'),max_length=100)
	username = models.CharField(verbose_name=('Nome de Usuário'),max_length=40)
	password = models.CharField(verbose_name=('Senha'),max_length=50)
"""

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'E-mail / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    
    """ Método deletar a imagem (avatar) quando alterada ou excluida """
    def delete(self):
        self.avatar.delete()
        return super(Dentist, self).delete()


    def _str_(self):
        return self.first_name or self.username

    def get_full_name(self):
        return ('%s  %s') % (self.first_name, self.last_name)

    def get_short_name(self):
        return str(self).split(" ")[0]

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class Categoria(models.Model):
    titulo = models.CharField(verbose_name="Título Categoria", max_length=200)

    def __str__(self):
        return self.titulo

        

class Anuncio(models.Model):
    titulo = models.CharField(verbose_name="Título", max_length=200)
    descricao = models.TextField(verbose_name="Descrição")
    preco = models.DecimalField(verbose_name="Preço", max_digits=5, decimal_places =2)
    tempo_uso = models.DateField(verbose_name="Data de compra")
    data_cadastro = models.DateTimeField(verbose_name="Data de criação", default=timezone.now)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagem = models.ImageField(verbose_name="Imagem",)

    def __str__(self):
        return self.titulo
        
	
class Question(models.Model):
	question_text = models.CharField(verbose_name="Texto da questão", max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text
		
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

anuncio/forms.py
from django import forms
#from django.contrib.auth.models import User
from . models import User,Categoria
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.forms import UserCreationForm

class LoginForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

"""class LoginForm(forms.Form):
	class Meta:
		model = CadastroUsuario
		fields = ('nome','contato','endereco','email','username','password')
		def __init__(self,*args,**kwargs):
			super().__init__(*args,**kwargs)
			self.helper = FormHelper()
			self.helper.form_method = 'post'
			self.helper.add_input(Submit('submit','Save Cadastro'))"""

class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'is_staff']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'is_active', 'is_staff']

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ['titulo']
        

anuncio/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from .models import User, Categoria
from .forms import LoginForm,CategoriaForm
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


class RegisterView(CreateView):

	model = User
	template_name = 'anuncio/register.html'
	form_class = LoginForm
	success_url = reverse_lazy('anuncio:login')



def index(request):
	return render(request,'anuncio/index.html');

def sobre(request):
	return render(request,'anuncio/sobre.html');
	
class CategoriaView(SuccessMessageMixin, CreateView):
	model = Categoria
	template_name = 'categoria/add_categoria.html'
	success_message = "Categoria criada com sucesso!"
	form_class = CategoriaForm
	success_url = reverse_lazy('anuncio:index')

anuncio/templates/anuncio/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Moveis Plus</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Moveis Plus</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'anuncio:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'anuncio:sobre' %}">Sobre Nós</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contato</a>
          </li>
          <!--<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contato</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>-->
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Pesquisar">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
        </form>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.username }}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Atualizar Dados</a>
              <a class="dropdown-item" href="#">Adicionar anuncio</a>
              <a class="dropdown-item" href="#">Histórico</a>
              <a class="dropdown-item" href="{% url 'anuncio:logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'anuncio:login' %}">Login</a>
          </li>
           <!-- <li class="nav-item dropdown">

            <!-- <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Login</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Logout</a>
            </div>
          </li>-->
          {% endif %}
          
        </ul>
      </div>
    </nav>

    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">{% block titulo_jumbtron %}{% endblock %}</h1>
      </div>

    </div>
    <div class="container">
    {% if messages %}
    
    {% for message in messages %}

    <div class="alert alert-{{ message.tags }} msg center">
        <span class="cent">{{ message }}</span>
    </div>
    {% endfor %}
    {% endif %}
    {% block conteudo %}
    {% endblock %}
    </div>
    <!-- Main jumbotron for a primary marketing message or call to action -->
      <hr>

      <footer>
        <p>&copy; Company 2018</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  </body>
</html>

anuncio/templates/anuncio/detail.html
<!-- Pega o texto da question e coloca no h1 -->
<h1>{{ question.question_text }}</h1>
<!-- Caso um erro seja lançado, imprime o texto do erro em negrito, tag <strong> -->
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!-- Início do formulário -->
<form action="{% url 'anuncio:vote' question.id %}" method="post">
<!-- Usa a tag de template {% csrf_token%} para prevenir ataques Cross Site Request Forgeries -->
{% csrf_token %}
<!-- Para cada choice associada a essa question -->
{% for choice in question.choice_set.all %}
    <!-- exibe um botão radio para cada opção da enquete associado ao ID da choice-->
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <!-- forloop.counter indica quantas vezes a tag for passou pelo laço -->
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<!-- Envia por POST o dado choice=#, onde o # é o ID da choice selecionada pra votar --> 
<input type="submit" value="Vote" />
</form>

anuncio/templates/anuncio/fomrLogin.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

anuncio/templates/anuncio/index.html
{% extends 'anuncio/base.html' %}
<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

{% block titulo_jumbtron %}Anúncios{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    

{% block conteudo %}
<p>conteudo</p>

{% endblock %}

anuncio/templates/anuncio/login.html
{% extends 'anuncio/base.html' %}
{% load widget_tweaks %}
{% block conteudo %}
<div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Não sabe onde comprar seus móveis?! Ficou perdido?</h1>
        <p>A federal móveis te ajuda a encotrar os melhores moveis usados da região de Picos. Temos ótimas opções
        para você escolher!</p>
        <p>Caso não seja cadastrado, faça seu registro <a href="{% url 'anuncio:register' %}">aqui</a>.</p>
        <p><!--<a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a>--></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row justify-content-md-center">
        <div class="col-md-6">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-4">Fazer Login</h1>
            <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
            <form action="." method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field|add_class:"form-control input-md" }}
                    </div>
                {% endfor %}
                <p><input type="submit" value="Enviar" /></p>
            </form>
          </div>
        </div>
        {% if form.errors %}
         <div class="alert alert-danger">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
             {{form.non_field_errors}}
         </div>
         {% endif %}
        </div>

      

         
         <!-- fim if novo -->

      

    </div>
</div>
{% endblock %}

anuncio/templates/anuncio/register.html
{% extends 'anuncio/base.html' %}
{% load widget_tweaks %}
{% block conteudo %}
<div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Não sabe onde comprar seus móveis?! Ficou perdido?</h1>
        <p>A federal móveis te ajuda a encotrar os melhores moveis usados da região de Picos. Temos ótimas opções
        para você escolher!</p>
        <p><!--<a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a>--></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row justify-content-md-center">
        <div class="col-md-6">
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h1 class="display-4">Registrar-se</h1>
            <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
            <form action="." method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field|add_class:"form-control input-md" }}
                    </div>
                {% endfor %}
                <p><input type="submit" value="Enviar" /></p>
            </form>
          </div>
        </div>
        </div>

    	

    </div>
</div>
{% endblock %}

anuncio/templates/anuncio/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

anuncio/templates/anuncio/sobre.html
{% extends 'anuncio/base.html' %}

{% block conteudo %}

<div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Site sobre Moveis</h1>
        <p>Os criadores foram obrigados a criar!</p>

      </div>
</div>

{% endblock %}

anuncio/templates/categoria/add_categoria.html
{% extends 'anuncio/base.html' %}
{% load widget_tweaks %}
<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

{% block titulo_jumbtron %}Adicionar Categoria{% endblock %}

<!-- Bloco de conteúdo da nossa página -->    
{% block conteudo %}
<form action="." method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field|add_class:"form-control input-md" }}
        </div>
    {% endfor %}
    <p><input type="submit" value="Enviar" /></p>
</form>

{% endblock %}